### ISSUE TITLE
binary insertion sort?

### ISSUE THREAD

**Issue by acicuc** [RobTillaart/RunningMedian#20]
Not an issue just a question relating to #10 and further development of the sorting algorithm...

I was wondering if a binary insertion sort may improve performance even further for single valued insertion into a sorted array? I'd implemented this in another library for finding write boundaries in a flash file system with ordered fixed width records and found it ran well - I often needed to find this (quickly) after a power cycle.

I'd also just like to say a big thanks for making this code available.

**Comment by RobTillaart** [comment]
Thanks for the question, 
Best way is to prototype this. My expectations are that it will depend on the size of the internal array if there is a performance gain.

**Comment by RobTillaart** [comment]
Another point is if there are identical values or not. 
If so the binary search should handle that to prevent unneeded moves.

What size are you using?
Anything you can tell about the values to be inserted?
Source, range, duplicates, ....

A variation might be a linear search that as first test checks halfway to skip 50% and goes linear from there. Would save the most steps (assuming random distribution)

**Comment by acicuc** [comment]
Actually at the moment I'm only using very small arrays up to about 20 or so for sensor medians and there's no really strong motivation, other than out of interest, to implement a binary search in the code. But I just thought I might ask where you might be heading regarding future development and whether you might be open to looking at other approaches.

The work I've done with flash files to find write boundaries (finding free space to safely write new data) showed a binary search was by far the most time efficient approach but we're talking searches over 100's of thousands of records and MB's of data on an Arduino. I mention it here as an example of using a binary search on larger data sets as it may be useful for larger arrays in your code.

Your suggestion of a 1/2 range linear search is almost how it works, but we just keep halving the search range with every comparison iteration, direction is determined by the comparison. It does require extra checks which would probably slow you down for small arrays but for anything larger you may get some benefit. It would be interesting to do some tests.

I've actually started modifying your code to allow for selecting the search method in anticipation of getting around to writing the bin search code but I'd shelved it until a burning need arises. In the coming months if nobody else has done it and I have some spare time I might have a go at prototyping something.

**Comment by RobTillaart** [comment]
I am familiar with binary search and many optimized versions of it. Overal it is fast however for small arrays it depends.

I am always open for improvements, and your suggestion is definitely an interesting one.which I will investigate today.

**Comment by RobTillaart** [comment]
created a test sketch for comparison.
```cpp
//
//    FILE: runningMedian_performance.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: test performance
//     URL: https://github.com/RobTillaart/RunningMedian

#include <RunningMedian.h>

// 50 consecutive samples from Sharp distance sensor model GP2Y0A710K0F while stationary.
const int sourceData[] =
{
  300, 299, 296, 343, 307, 304, 303, 305, 300, 340,
  308, 305, 300, 304, 311, 304, 300, 300, 304, 304,
  284, 319, 306, 304, 300, 302, 305, 310, 306, 304,
  308, 300, 299, 304, 300, 305, 307, 303, 326, 311,
  306, 304, 305, 300, 300, 307, 302, 305, 296, 300
};

const int sourceSize = (sizeof(sourceData) / sizeof(sourceData[0]));

// RunningMedian samples = RunningMedian(sourceSize);
RunningMedian samples = RunningMedian(sourceSize / 2);

void setup()
{
  Serial.begin(115200);
  while (!Serial);  //  Wait for serial port to connect. Needed for Leonardo + MKR1010.
  delay(1000);
  Serial.print(F("Running Median Version: "));
  Serial.println(RUNNING_MEDIAN_VERSION);


#ifdef RUNNING_MEDIAN_USE_MALLOC
  Serial.println(F("Dynamic version using malloc() enabled"));
#else
  Serial.print(F("Static version, will always allocate an array of "));
  Serial.print(MEDIAN_MAX_SIZE, DEC);
  Serial.println(F(" floats."));
#endif

  test1();

  Serial.println("\ndone..\n");
}

void loop()
{
}

void test1()
{
  uint32_t start = 0;
  uint32_t total = 0;

  Serial.print(F("Allocated size = "));
  Serial.println(samples.getSize());
  Serial.println();

  Serial.print(F("50 x add: "));
  for (uint8_t i = 0; i < sourceSize; i++)
  {
    start = micros();
    samples.add(sourceData[i]);
    total += (micros() - start);
  }
  Serial.print(F("50 x add: "));
  Serial.println(total);
  Serial.print(F("     avg: "));
  Serial.println(total / 50.0);
}

// -- END OF FILE --
```

output:
```
Running Median Version: 0.3.6
Dynamic version using malloc() enabled
Allocated size = 25

50 x add: 50 x add: 580
     avg: 11.60

done..
```

**Comment by RobTillaart** [comment]
So an Arduino UNO uses 11.60 micros per addition. It does not sort, only set the flag. 
Now I need to extend the example with sorting / access

**Comment by RobTillaart** [comment]
got a small performance gain by splitting the inner loop of the sort into two loops.
Expect it improved the use of (limited) registers
```cpp
void RunningMedian::sort()
{
  // insertSort
  for (uint16_t i = 1; i < _count; i++)
  {
    uint16_t z = i;
    uint16_t temp = _sortIdx[z];
    while ((z > 0) && (_values[temp] < _values[_sortIdx[z - 1]]))
    {
      // _sortIdx[z] = _sortIdx[z - 1];
      z--;
    }
    uint16_t k = i;
    while (k > z)
    {
      _sortIdx[k] = _sortIdx[k - 1];
      k--;
    }
    _sortIdx[z] = temp;
  }
  _sorted = true;
}
```

results in ~8% better
```
Running Median Version: 0.3.6
Dynamic version using malloc() enabled
Allocated size = 25

50 x add: 588
     avg: 11.76
 1 x get: 1192       == sorting
  median: 304.00
 1 x get: 12       == no sorting
  median: 304.00

done..
```

**Comment by RobTillaart** [comment]
After several test runs I got binary insertion working. Might be optimized even further.
```cpp
void RunningMedian::sort()
{
  uint16_t lo   = 0;
  uint16_t hi   = 0;
  uint16_t mi   = 0;
  uint16_t temp = 0;

  // insertSort
  for (uint16_t i = 1; i < _count; i++)
  {
    temp = _sortIdx[i];
    float f = _values[temp];

    //  find insertion point
    //  handle special case first
    if (f <= _values[_sortIdx[0]])
    {
      hi = 0;
    }
    else
    {
      lo = 0;
      hi = i;
      while (hi - lo > 1)
      {
        mi = (lo + hi) / 2;
        if (f < _values[_sortIdx[mi]])
        {
          hi = mi;
        }
        else
        {
          lo = mi;
        }
      }
    }

    //  move all to make space
    uint16_t k = i;
    while (k > hi)
    {
      _sortIdx[k] = _sortIdx[k - 1];
      k--;
    }

    //  insert at right spot.
    _sortIdx[k] = temp;

  }
  _sorted = true;

  //  verify sorted
  // for (int i = 0; i < _count; i++)
  // {
    // Serial.print(i);
    // Serial.print("\t");
    // Serial.println(_values[_sortIdx[i]]);
  // }
}
```
results are almost 40% faster (for this test case)
```
Running Median Version: 0.3.6
Dynamic version using malloc() enabled
Allocated size = 25

50 x add: 588
     avg: 11.76
 1 x get: 784       == sorting
  median: 304.00
 1 x get: 8       == no sorting
  median: 304.00

done..
```

**Comment by RobTillaart** [comment]
Did some test runs


|  buffer size  |   new sort  |  old sort  |
|:-------------:|:-----------:|:----------:|
|   50          |    2252     |   4052     |
|   25          |     748     |   1300     |
|   10          |     208     |    260     |
|    5          |      72     |     84     |
|    4          |      68     |     52     |  
|    3          |      36     |     28     |

So only for very small sizes the straightforward insertion is faster.

Note: the library is grown by about ~80 bytes. 
So if RAM is more important than performance, use the old sort().

**Comment by RobTillaart** [comment]
> I was wondering if a binary insertion sort may improve performance even further for single valued insertion into a sorted array?

So the answer is yes 😎

**Comment by RobTillaart** [comment]
I am creating a 0.3.7 version in the develop branch a.s.a.p.

**Comment by RobTillaart** [comment]
Created - https://github.com/RobTillaart/RunningMedian/tree/develop

**Comment by RobTillaart** [comment]
@acicuc 

There exist a variation on quicksort that can be used to find the median without actually sorting the array.

It works something like this:

Selects a pivot to split the array in a part smaller than the pivot and a part larger than the pivot.
Then do a recursive call for the partition that has the Nth element in it.

pseudo code
```cpp
float getMedian()
{
  return find_nth_element(&array, lo, hi, (lo+hi)/2);  
}

float find_nth_element(&array, lo, hi, n)
{
  if lo == hi) return element(lo);

  // select pivot
  pos = (lo + hi) / 2;
  pivot = element(pos)
  // swap all elements < to the left and > to the right
  
  // select partition in which nth element lies
  if (n < pos)   return find_nth_element(&array, lo, pos, n)
  return find_nth_element(&array, pos, hi, n)
}
```

Notes:
- ok one should cache the found value until new elements are added. (like sorted flag)
- recursive calls are relative expensive so it might not work that fast.

**Comment by acicuc** [comment]
That's a lot of work in just a few hours! The results look excellent and I'm glad you're incorporating the new method in the next version.

I think an 80 byte increase in RAM usage won't be a problem for most applications. 

I worked out the theory behind a linear vs binary search this morning during breakfast. I wanted to know what the transition point (number of array elements n) would be when we'd see time parity based on an assumed slower iteration cycle for the binary search. It turns out if the binary loop is 2x slower than the linear you'd see time parity at around n=5, which is I guess what you've just discovered through testing. But at n=16 we should see a binary search at 2x times faster than a linear, at n=144 bin should be 10x faster...as you can see we should see big gains for larger arrays. I can send you my notes on this if you'd like.

But great work there and thanks for the huge effort in such a short time frame. I look forward to studying what you've done more closely in the coming days.

**Comment by RobTillaart** [comment]
> That's a lot of work in just a few hours! The results look excellent and I'm glad you're incorporating the new method in the next version.

Thank you,

> I worked out the theory ....

"In theory there is no difference between theory and practice but in practice there is."

Your math looks correct, binary search is O(log n) where linear search is O(n) . {big O notation is order of magnitude).
In practice a lot of work is done in shifting, which takes most of the time  O(n^2).
From theory a linked list implementation should be fastest as insertion is O(n). 

> I think an 80 byte increase in RAM usage won't be a problem for most applications.

Agree, but as that is an assumption, therefor I left the original sort in the code (.cpp file).

There are many options to improve performance, but code should for all be maintainable. If I look at my code in 3 months I don't want to ask "who wrote this, what was I thinking, how does it work, etc".

If you have time could you test the new branch in your code?

>  I look forward to studying what you've done more closely in the coming days.

There is a new example that I used for testing. 
Just add some print statements in the sorting (lo mi hi) to see what happens.

**Comment by acicuc** [comment]
No worries testing in my code, but it'll probably be at the end of the week.

**Comment by acicuc** [comment]
I've completed some testing this morning and it all looks to be running well. I used a board with a SAMD21 (equivalent to an Arduino Zero). I also used pseudo randomly generated signed integers as sort values with array sizes up to your max of 255. 

From my testing results show at n=255 bin search is at least 4x faster than the previous insert sort. Time parity is at around n=25. Bin search is 2x faster at around n=60.

It may be useful to keep the linear search in there for arrays of size less than 25 and have an auto select or user based option to choose. However, there could also be ways to optimise the bin search further to improve its speed for smaller arrays.

**Comment by RobTillaart** [comment]
Thanks for this feedback, very valuable.
It seems that parity depends on processor used. With my UNO it was somewhere around 5.

If you have a short buffer e.g 5, 11 or 13 elements, is lineair search much faster or comparable?

I think of making a derived class that uses the binary search. A runtime flag to select means a larger footprint as both codes need to be in. A derived class has exact the same interface, and can be selected compile time. My assumption is that very few projects will have a need to change it run-time.

A possible optimization of the search is one that remembers the position of the last inserted element. Will give more gain in the linear search than in the binary. (Just to keep the thought)

**Comment by RobTillaart** [comment]
> I think of making a derived class that uses the binary search. 

@acicuc Any idea for a descriptive name?

**Comment by acicuc** [comment]
I'm using the 'develop' and 'master' branch for comparisons, is that correct?

If a compile time sort selection, I wouldn't think a derived class would be necessary, a compiler '#if #else' directive would probably do to contain the two different versions of 'sort()'. A '#define' can be used for selection. I've no preference for naming.

Regarding optimisation: My head is in this space now so I may dedicate a little more time for testing some ideas in the next couple of weeks. I've already made a 'sort on add version' which spreads the load across calls making it less blocking when a median is requested. By the way it is marginally slower due to the extra functional calls and it's not completely nailed down in terms of sorting just yet...

**Comment by RobTillaart** [comment]
Thanks,
Mist interesting algorithm to investigate would be quick select. This is quick sort derived and does no full sorting to get the k-th element. So the number of moves would be reduced.

**Comment by RobTillaart** [comment]
@acicuc 
- Merged the code of the two sorts into one
- added a **setSearchMode(mode = 0)** 0 = linear, 1 is binary 
- improved the test sketch to compare both modes in one run.
- updated readme.md etc.
- left all old code in .cpp file

results of the new sketch
```
Running Median Version: 0.3.7
Dynamic version using malloc() enabled

Allocated size = 25
nr of elements = 0
    searchMode = 0

50 x add: 532
     avg: 10.64
 1 x get: 1144       == sorting
  median: 304.00
 1 x get: 12       == no sorting
  median: 304.00

Allocated size = 25
nr of elements = 0
    searchMode = 1

50 x add: 524
     avg: 10.48
 1 x get: 792       == sorting
  median: 304.00
 1 x get: 8       == no sorting
  median: 304.00

done..
```

Please give it a try with your 255 element test.

**Comment by RobTillaart** [comment]
Merged the develop branch and released the 0.3.7 version (in progress). 
I close the issue as the original question is now solved (even if the discussion can continue)

If you have test results, please share them here as they might trigger additional developments.

**Comment by acicuc** [comment]
A nice merge of the two methods there @RobTillaart. 

I've also completed some testing of a new version, see [svBin](/acicuc/RunningMedian/tree/svBin), compared to the others - [results](https://github.com/acicuc/RunningMedian/blob/svBin/test/RunningMedian_tests.pdf). Speed wise it looks quite good - especially for single value insertion+sort, which is my main focus. 

This new version sorts (binary) as you go when adding values to the buffer spreading the computational load across calls. The only thing I'm still thinking about is how to find the oldest value quickly without having to resort to a linear search - another bin search perhaps! I did also think about dropping the use of the sort index and just manipulating the array as the values come in but quickly realised you'd lose track of you're oldest values, the sort index is kind of essential there.

**Comment by RobTillaart** [comment]
Think The fastest implementation would use an array of nodes in rime order. Each node has pointers of its place in sort order. These pointers build up a binary tree.

When inserting a new element, one can use the oldest index to remove the oldest node from the tree. Then search the place to insert the new node in the tree again.

Drawback it uses a more memory and inserting deleting in the tree takes time too. In theory a operations would be O(log(n)) or better.

**Comment by RobTillaart** [comment]
A linked list instead of a tree is simpler code wise but searching is O(n).

**Comment by RobTillaart** [comment]
I had a quick look and if I understand correctly you keep the elements sorted at every addition so the median can be found very fast after that. 
I did a similar implementation in the past and if I recall correctly it comes down to three factors
- the ratio of add() calls and getMedian() calls
- the grouping of the add() calls.
- internal array size

If #add() >> #get(),  sorting during get is most efficient
if #add() << #get(), sorting during add is most efficient as you can use the fact that the data is nearly sorted.
Once sorted get() will not sort again - you can even cache the median.
if #add()~ #get() it depends if the add() calls are consecutive in larger groups or if there is a (near perfect) alternating rythm with the get() calls
With this latter case the size of the internal array defines where the threshold lies for optimal sorting.

In my implementation I have chosen to assume that there will more add()  calls than get() calls in most projects.

So to make performance measurements one must include both add() and get()  into the equation. 
Furthermore be aware that if you optimize for your specific case it might be less efficient in other cases.
(or footprint whatever)

That said, it is very interesting research you do.

#### food for thought

If RAM is no issue you might keep 2 arrays, one in time order, the other in value order.  
If you need to remove a measurement both arrays can be updated in O(n) or faster 
NB in the value order if you have 5x the value 200 and you need to remove 1 of them, you can pick the efficient one.

**Comment by acicuc** [comment]
Your assessment sounds pretty much spot on!

I should have also mentioned the test results are total time for add+get, for example a '5x5' test is n=5, start with empty buffer then 5xadd + 1xget. A '5x1' is n=5, start from full buffer then 1xadd + 1xget.

> Furthermore be aware that if you optimize for your specific case it might be less efficient in other cases.

Having some test results helps a lot in deciding which way to go. You can see svBin is by far the best approach for buffers >= 5 for a single add+get but only starts to dominate for multi-add + 1 get for larger arrays.

> food for thought
If RAM is no issue you might keep 2 arrays, one in time order, the other in value order.
If you need to remove a measurement both arrays can be updated in O(n) or faster
NB in the value order if you have 5x the value 200 and you need to remove 1 of them, you can pick the efficient one.

I'd considered both of these. The problem with another array is you have more operations to complete and thus takes additional time which will slow down the whole process. A binary search on ordered values would be the fastest but duplicates present a problem because you may end up removing values that aren't the oldest...which leads to a mess! 
A variation is to use bin search on ordered values, once found check the indices match; if not we've found a duplicate so then use linear across the duplicate set until the indices match. This approach could end up being more expensive than straight linear if the buffer is full of duplicates.

**Comment by RobTillaart** [comment]
Another idea

Instead of a flag indicating sorted or not, one could count the additions since last sorting. Works equally well as flag however:
If only a few adds are done, e.g less than 20% of the size, a bubble sort might be faster.  Most of the array will still be sorted.

**Comment by acicuc** [comment]
I actually removed that flag in svBin as no longer needed due to sorting as you go - one less operation.

Still lots of interesting things that could be looked at but for the moment I'm pretty happy with where we're at with your new version and also my fork. If I feel inspired at some point in the future I might pick it up again. 

Thanks for taking the time to look at this and integrating the ideas into your code.

**Comment by RobTillaart** [comment]
> I actually removed that flag in svBin as no longer needed due to sorting as you go - one less operation.

True, however such flag is not the "performance eater".
Imagine a stream of data with (a lot of) duplicates, checking if the new value is identical removes the need for sorting.
Might be interesting to check for your svBin version.

As the interface of the svBin is still identical, it might be added as a derived or base class.
(hierarchy to be discussed).

> Thanks for taking the time to look at this and integrating the ideas into your code.

Welcome,
