### ISSUE TITLE
Multiple Sensors

### ISSUE THREAD

**Issue by christianmerges** [RobTillaart/RunningMedian#24]
Hello,

thanks for providing the lib. I wanna use it for multiple sensors. How can I sample multiple sensors the same time? I was thinking about duplicating the library and rename it, but there has to be an easier way. It's not really an issue, but I didn't found any other way to get in touch with u.

**Comment by NuclearPhoenixx** [comment]
Do you mean you want multiple moving medians at the same time for different sensors? That's easy, just use a different instance for every sensor:

```cpp
RunningMedian <name> = RunningMedian(5);
```

You only need to adjust `<name>` like this:

```cpp
RunningMedian a = RunningMedian(5);
RunningMedian b = RunningMedian(5);
RunningMedian c = RunningMedian(5);
```

And then go from there. Hope that helps!

**Comment by RobTillaart** [comment]
You can even create an array of RunningMedian objects.

See the example **RunningMedian_array.ino**

https://github.com/RobTillaart/RunningMedian/blob/master/examples/RunningMedian_array/RunningMedian_array.ino

**Comment by christianmerges** [comment]
> RunningMedian a = RunningMedian(5);
> RunningMedian b = RunningMedian(5);
> RunningMedian c = RunningMedian(5);

so this is kinda initializing for the sensors a , b and c with a sample size of 5 each?

**Comment by NuclearPhoenixx** [comment]
Well, yes it's initializing 3 different running medians with sample size of 5 each. What you do with a, b and c is 100% up to you. You can put all the info of sensor 1 into a, 2 into b and so on and you get three different medians for each sensor.

**Comment by RobTillaart** [comment]
@christianmerges 
If this solves your issue, you may close it
