### ISSUE TITLE
Maximum of Size = 19

### ISSUE THREAD

**Issue by pkoevesdi** [RobTillaart/RunningMedian#4]
I successfully use this library on a ESP8266. Now I realized, the the maximum of the size to allocate with `RunningMedian samples = RunningMedian(x);` is x=19. If I try more, the size inquired with `samples.getSize();` stays at 19.
How can this be explained? I there a way of taking more samples?

**Comment by RobTillaart** [comment]
@pkoevesdi 

Change line 25 in runningMedian.h 

#define MEDIAN_MAX_SIZE     19   ==>  42  (whatever your typical max number)

Give it a try

**Comment by RobTillaart** [comment]
Note the library hard allocates MEDIAN_MAX_SIZE  floats and pointers so be careful not to set it too high.

(it was set to 19 as a reasonable max value for most apps on UNO,

**Comment by pkoevesdi** [comment]
Great, this works, Thank You very much!
Would You consider adjusting Your examples to this default max value? It is confusing that the examples _seem_ to use higher sizes than they actually do.
I'd set it to 100, would You consider this too high?
Now, how can I set it inside my own program, overriding RunningMedian.h? I tried it with defining before including, but that doesn't work. I'd like to be upgrade-proof.

**Comment by RobTillaart** [comment]
> I'd set it to 100, would You consider this too high?

The nr 19 is based on the memory limits of UNO and even smaller devices in the arduino ecosystem. Newer boards like ESP have much more RAM so 100 is not a problem. For performance you better take an odd number like 101 as the median is the middle element and with an odd number less math is needed. Only an issue if performance is an issue .

> I'd like to be upgrade-proof.
I'm investigating quickly some ideas, expect an update of the lib today with the command line define overruling as a start.

**Comment by pkoevesdi** [comment]
Great, looking forward.

**Comment by RobTillaart** [comment]
First step is done 
- added files + config for automatic build an minor unit test so I can see if I break something.
- added the option for compile time defining the MEDIAN_MAX_SIZE, but not all environments allow you to set them,

To be continued.

**Comment by RobTillaart** [comment]
@pkoevesdi 
Please check the branch **allsize** which uses dynamic memory.
It is not 100% tested yet and it need cleanup, but it is the way I want to go..

The minimum of elements might become 3.
For the case you want to follow a constant signal and allow an occasional single outlier.

**Comment by pkoevesdi** [comment]
Ok, just made a short test with unchanged RunningMedian from branch allsize. 
```
RunningMedian samples = RunningMedian(101);
```
works as expected in my program.
Thank You very much for this quick solution!

**Comment by RobTillaart** [comment]
https://github.com/RobTillaart/RunningMedian 0.3.0 released
- max size is set to 250 elements.
- memory is allocated dynamically, so it is as small / large as needed 

Please let me know if  there are new issues.

**Comment by pkoevesdi** [comment]
Works fine in my setup.
Maybe set the maximum to 255? This is what the input datatype of `RunningMedian()` allows and thus what a user might expect to be allowed to set. If I set more than 255, I get at least a compiler warning. Now, if the user sets for instance 253, he gets nothing, but wonders, why the window size is 250, not 253.
And in the Readme, there's still the note about the 19, which is not valid any more. (Not in default configruation).

Thank you anyway for the work. Any special way I can repay?

**Comment by RobTillaart** [comment]
> Maybe set the maximum to 255? 

Could be, Did that to prevent overflow of uint8_t size and count etc which I used to minimize footprint (think tiny85 or so) 
Need some good tests to see that the lib does not fail while sorting internally etc. when using 255. 
As I have ~100 libraries that need attention, this was a safe way to release it fast. 

> Now, if the user sets for instance 253, he gets nothing

In the future I could do the allocation in a **begin()**  or a **setSize()**  function which could return success / fail or the numbers allocated. Constructor is a bad choice in fact to do the allocation, for now backwards compatibility was chosen. 

> And in the Readme, there's still the note about the 19, which is not valid any more. (Not in default configuration).

Some things slip through, sorry. I'll make an issue to check the readme on the details.

> Thank you anyway for the work. 

You're welcome, 

> Any special way I can repay?

If you insist, donate to local charity (money or time) as there are plenty of people in the world that have serious needs.

**Comment by RobTillaart** [comment]
Opened issue #7 and #8 as said.

**Comment by pkoevesdi** [comment]
Ok, thanks for clarification and the new issues.
And thanks for inducing me to give some money, it's been a while ago. Sent 30 EUR to unicef...

**Comment by RobTillaart** [comment]
Did a test with using intern admin uint16_t allowing to really bigger buffers - seems to work.

Problem that pops up is that the sorting takes serious amount of time.

made a testsketch that adds an element and request an element every loop()
- at 300 elements it takes 335 milliseconds on an UNO to **getMedian()** which triggers sorting.
- at 30 elements it takes  < 4 milliseconds. so 10x more elements = 100x more time.

Serious too long - and that is an understatement.
TODO
- investigate insertion sort (or others) 
- investigate sorting during the Add
- add a flag to switch when sorting? 
  - some apps add continuously and request very few or other way around.
  - 

![image](https://user-images.githubusercontent.com/462844/104813547-16c72800-580a-11eb-973e-20ed4b6f572d.png)

**Comment by RobTillaart** [comment]
with uint8_t and max 255 the results are pretty similar.

As we insert one element in an already sorted list the amount of elements moved is on average 50% of the list.

A linked list would perform better but that takes quit a bit extra memory. To be investigated...

![image](https://user-images.githubusercontent.com/462844/104817605-93660080-5822-11eb-8af4-55118589a88c.png)

**Comment by RobTillaart** [comment]
@pkoevesdi 
Investigation done, bubblesort replaced by insertionSort 
=> way faster for large internal buffer, Solved in c3de2e1 Release 0.3.2

**Comment by pkoevesdi** [comment]
Great, thanks. Since I don't have the speed problem in this project, I cannot confirm or neglect. Tell me, if You want me to do some explicit testing, maybe pass me code to test with.

**Comment by RobTillaart** [comment]
@pkoevesdi 
Just to let you know things have changed and (hopefully) the performance improved.  

You might do a recompile of your projects that use the runningMedian.
Would be a better test as those are different than my projects.

**Comment by pkoevesdi** [comment]
Ok, I recompiled and made a short function check, everything seems good and working as before.
